# Generated by Django 6.0.5 on 2026-05-26 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя исполнителя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование коллекции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание коллекции')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Состояние')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание состояния')),
                ('grade', models.CharField(max_length=10, verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Состояние',
                'verbose_name_plural': 'Состояния',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название лейбла')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание лейбла')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Лейбл',
                'verbose_name_plural': 'Лейблы',
            },
        ),
        migrations.CreateModel(
            name='VinylFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Формат')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание формата')),
                ('speed', models.CharField(max_length=50, verbose_name='Скорость вращения')),
            ],
            options={
                'verbose_name': 'Формат пластинки',
                'verbose_name_plural': 'Форматы пластинок',
            },
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование пластинки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание пластинки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/plates/%Y/%m/%d/', verbose_name='Изображение')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_exist', models.BooleanField(default=True, verbose_name='Доступна к заказу')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productproject.artist', verbose_name='Исполнитель')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productproject.category', verbose_name='Категория')),
                ('collection', models.ManyToManyField(blank=True, to='productproject.collection', verbose_name='Коллекции')),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productproject.condition', verbose_name='Состояние')),
                ('genre', models.ManyToManyField(blank=True, to='productproject.genre', verbose_name='Жанры')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productproject.label', verbose_name='Лейбл')),
                ('vinyl_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productproject.vinylformat', verbose_name='Формат')),
            ],
            options={
                'verbose_name': 'Пластинка',
                'verbose_name_plural': 'Пластинки',
            },
        ),
    ]
