# Generated by Django 6.0.5 on 2026-05-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='artists/%Y/%m/%d/', verbose_name='Фото исполнителя'),
        ),
        migrations.AddField(
            model_name='label',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='labels/%Y/%m/%d/', verbose_name='Логотип лейбла'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='plates/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
